### ISSUE TITLE
Copygen

### ISSUE THREAD

**Issue by grace764** [aasharck/aasharck#1]
Copygen is not working please check

**Comment by aasharck** [comment]
Sure. Will look into it.

P.S - Never knew this website had users. By the way, I know it doesn't work everytime and also it doesnt work with some websites like Aliexpress. Will try to solve all of these soon.

**Comment by grace764** [comment]
> Sure. Will look into it.
> 
> P.S - Never knew this website had users. By the way, I know it doesn't work everytime and also it doesnt work with some websites like Aliexpress. Will try to solve all of these soon.

This website is really awesome. Yes I know some website will not work, it was working very good with Amazon, Alibaba and Shopify website but recently getting error
[](https://postimg.cc/xJFB6Xcv)

https://i.postimg.cc/cCsZ4YWb/Screenshot-2023-07-12-140703.png

**Comment by aasharck** [comment]
Thanks! I am looking into it. Will try to solve it soon.

**Comment by aasharck** [comment]
Hi, Thanks a lot for your patience.
The site is now up and running.

Please open a new issue or contact me at aasharck@gmail.com if you want any new features to be added or if you need any help.

Thanks again

**Comment by grace764** [comment]
Result text is in grey and difficult to read earlier text was in white

https://i.imgur.com/gWbfld0.png

**Comment by aasharck** [comment]
Sorry for that, Just made the change. 
Thank you

**Comment by grace764** [comment]
Still text is not clear in ad copy

https://i.imgur.com/SXpgWwp.png

**Comment by aasharck** [comment]
Fixed it. please check.

**Comment by grace764** [comment]
Getting error to access site

https://i.imgur.com/e1kapz5.png

**Comment by aasharck** [comment]
Might have been a server issue at that time.
It's working fine for me

**Comment by grace764** [comment]
Hi unable to access website https://www.copygen.xyz/

**Comment by aasharck** [comment]
Hi,
I actually don't have the funds to keep this project running.
So, I am planning to shut it down.

But, if this tool has helped you and you think it can help other ecommerce entrepreneurs, let me know. I want to make it better and make it paid as well.
